apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-app
  labels:
    app: cust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cust-app
  template:
    metadata:
      labels:
        app: cust-app
    spec:
      containers:
        - name: cust-app
          image: rajesh4113/cust-app:latest   # tag will be overridden by imagePullPolicy: Never + loaded image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
