apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cust-app
  template:
    metadata:
      labels:
        app: cust-app
    spec:
      containers:
      - name: cust-app   # must match Jenkins set-image target
        image: rajesh4113/cust-app:latest
        ports:
        - containerPort: 5000
