apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cust-app
  template:
    metadata:
      labels:
        app: cust-app
    spec:
      containers:
        - name: cust-app
          image: cust-flask:IMAGE_TAG
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
