apiVersion: apps/v1
kind: Deployment
metadata:
  name: cust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cust-app
  template:
    metadata:
      labels:
        app: cust-app
    spec:
      containers:
      - name: cust-app
        image: 423014875134.dkr.ecr.ap-south-1.amazonaws.com/cust-jenkins-docker-build:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
